# Generated by Django 5.0.3 on 2024-03-18 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsahverse', models.CharField(max_length=100)),
                ('cisloverse', models.IntegerField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Kniha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=64)),
                ('kapitola', models.IntegerField(max_length=60)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kniha', to='Biblecz.vers')),
            ],
        ),
    ]
