# Generated by Django 5.0.3 on 2024-04-01 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kapitola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislokapitoly', models.IntegerField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsahverse', models.CharField(max_length=60)),
                ('cisloverse', models.IntegerField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Kniha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazevknihy', models.CharField(max_length=60)),
                ('zkratkaknihy', models.CharField(max_length=60)),
                ('kapitola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kniha', to='Biblecz.kapitola')),
            ],
        ),
        migrations.AddField(
            model_name='kapitola',
            name='vers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kapitola', to='Biblecz.verse'),
        ),
    ]
