# Generated by Django 5.0 on 2024-04-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kniha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazevknihy', models.CharField(max_length=60)),
                ('zkratkaknihy', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Kapitola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislokapitoly', models.IntegerField()),
                ('kniha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kapitoly', to='Biblecz.kniha')),
            ],
        ),
        migrations.CreateModel(
            name='Vers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsahverse', models.CharField(max_length=1000)),
                ('cisloverse', models.IntegerField()),
                ('kapitola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse', to='Biblecz.kapitola')),
            ],
        ),
    ]
